name: 기능 제안
description: 새로운 기능과 구현 방향을 제안합니다.
title: "기능 제안: AI 문서 개요 자동 생성 (AI Outline Generator)"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        아래 항목을 채우면 `#28` 이슈와 동일한 구조로 기능 제안을 작성할 수 있습니다.

        제목은 아래 형식으로 직접 완성해 주세요.
        `기능 제안: {기능명} ({영문명})`

  - type: input
    id: feature_name_ko
    attributes:
      label: 기능명 (한글)
      placeholder: 예) 문서 목표 기반 작성 모드
      value: AI 문서 개요 자동 생성
    validations:
      required: true

  - type: input
    id: feature_name_en
    attributes:
      label: 기능명 (영문)
      placeholder: 예) Goal-Oriented Writing Mode
      value: AI Outline Generator
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: 개요
      description: 현재 문제와 기능 필요성을 2~4문장으로 작성해 주세요.
      placeholder: |
        현재 캔버스/채팅 흐름에서 ...
        이로 인해 ... 문제가 있습니다.
        따라서 ... 기능이 필요합니다.
      value: |
        현재는 사용자가 빈 캔버스에서 문서 구조를 처음부터 직접 설계해야 해서 시작 장벽이 큽니다.
        특히 목표(목적/독자/톤)가 정해져 있어도 섹션 구성까지 수동으로 만드는 데 시간이 많이 소요됩니다.
        따라서 목표와 대화 맥락을 기반으로 초기 목차/개요를 자동 제안하는 기능이 필요합니다.
    validations:
      required: true

  - type: textarea
    id: proposed_features
    attributes:
      label: 제안 기능
      description: 핵심 기능을 불릿 3~5개로 작성해 주세요.
      placeholder: |
        - ...
        - ...
        - ...
      value: |
        - CommandBar 또는 캔버스 툴바에서 "개요 생성" 액션 제공
        - activeWritingGoal, 최근 대화, 현재 캔버스 내용을 기반으로 섹션 트리 생성
        - 생성된 개요를 미리보기 모달에서 항목별 선택/해제 후 적용
        - 적용 시 캔버스에 마크다운 헤더 구조(`#`, `##`)로 삽입
        - 기존 DiffPreview와 동일하게 적용 전/후 비교 제공
    validations:
      required: true

  - type: textarea
    id: state_extension
    attributes:
      label: 구현 방향 - 상태 구조 확장
      description: TypeScript 인터페이스 예시 1개와 저장 위치(useStore/settings)를 작성해 주세요.
      render: typescript
      placeholder: |
        interface ExampleState {
          id: string;
          name: string;
        }

        // useStore에 추가
        exampleState: ExampleState | null;
      value: |
        interface OutlineDraft {
          id: string;
          title: string;
          sections: string[];
          createdAt: string;
        }

        interface AppState {
          pendingOutlineDraft: OutlineDraft | null;
          isOutlinePreviewOpen: boolean;
        }
    validations:
      required: true

  - type: textarea
    id: implementation_tasks
    attributes:
      label: 구현 방향 - 주요 작업
      description: 체크박스 형식으로 4~7개 작업 항목을 작성해 주세요.
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
        - [ ] 작업 3
        - [ ] 작업 4
      value: |
        - [ ] Phase 1 프롬프트에 "개요 생성" 모드 추가
        - [ ] 개요 응답 스키마(Zod) 및 파서 확장
        - [ ] Zustand에 pendingOutlineDraft / preview open 상태 추가
        - [ ] 개요 미리보기 UI(선택 적용) 추가
        - [ ] 선택된 개요를 마크다운 헤더로 캔버스에 반영하는 액션 구현
        - [ ] 개요 생성/적용 시나리오 테스트 추가
    validations:
      required: true

  - type: textarea
    id: expected_impact
    attributes:
      label: 기대 효과
      description: 기대 효과를 불릿 2~4개로 작성해 주세요.
      placeholder: |
        - ...
        - ...
      value: |
        - 문서 작성 시작 시간을 줄여 초기 생산성을 높일 수 있습니다.
        - 목표 기반(독자/톤/길이) 문서 구조 일관성이 향상됩니다.
        - 초보 사용자도 구조화된 문서를 더 쉽게 작성할 수 있습니다.
    validations:
      required: true

  - type: checkboxes
    id: validation_checklist
    attributes:
      label: 확인 사항
      options:
        - label: "제목을 `기능 제안: {기능명} ({영문명})` 형식으로 작성했습니다."
          required: true
